GO ?= go
DETECTED_LIBNBD_VERSION = $(shell dpkg-query --showformat='$${Version}' -W libnbd-dev || echo "0.0.0-libnbd-not-found")
SPHINXENV=doc/.sphinx/venv/bin/activate
SPHINXPIPPATH=doc/.sphinx/venv/bin/pip

default: build

.PHONY: build
build: build-dependencies migration-manager
	$(GO) build -o ./bin/migration-managerd ./cmd/migration-managerd
	$(GO) build -o ./bin/migration-manager-worker ./cmd/migration-manager-worker

.PHONY: build-dependencies
build-dependencies:
	@if ! dpkg --compare-versions 1.20 "<=" ${DETECTED_LIBNBD_VERSION}; then \
		echo "Please install libnbd-dev with version >= 1.20"; \
		exit 1; \
	fi

.PHONY: migration-manager
migration-manager:
	mkdir -p ./bin/
	CGO_ENABLED=0 GOARCH=amd64 $(GO) build -o ./bin/migration-manager.linux.amd64 ./cmd/migration-manager
	CGO_ENABLED=0 GOARCH=arm64 $(GO) build -o ./bin/migration-manager.linux.arm64 ./cmd/migration-manager
	CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 $(GO) build -o ./bin/migration-manager.macos.amd64 ./cmd/migration-manager
	CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 $(GO) build -o ./bin/migration-manager.macos.arm64 ./cmd/migration-manager
	CGO_ENABLED=0 GOOS=windows GOARCH=amd64 $(GO) build -o ./bin/migration-manager.windows.amd64.exe ./cmd/migration-manager
	CGO_ENABLED=0 GOOS=windows GOARCH=arm64 $(GO) build -o ./bin/migration-manager.windows.arm64.exe ./cmd/migration-manager

.PHONY: build-all-packages
build-all-packages:
	$(GO) mod tidy
	$(GO) build ./...
	$(GO) test -c -o /dev/null ./...

.PHONY: build-ui
build-ui:
	$(MAKE) -C ui

.PHONY: test-ui
test-ui:
	$(MAKE) test -C ui

.PHONY: test
test: build-dependencies
	$(GO) test ./... -v -cover

.PHONY: install
install: build build-ui
	@if ! test -e ./worker/mkosi.output/migration-manager-worker.raw ; then \
		$(MAKE) -C worker; \
	fi

	sudo install -D -m755 ./bin/migration-managerd /usr/bin/migration-managerd
	sudo install -D -m755 ./bin/migration-manager.linux.amd64 /usr/bin/migration-manager
	sudo install -D -m755 ./bin/migration-manager-worker /usr/lib/migration-manager/migration-manager-worker
	sudo install -D -m755 ./worker/mkosi.output/migration-manager-worker.raw /var/cache/migration-manager/worker-x86_64-v$(shell /usr/bin/migration-manager --version).img
	sudo install -d -m755 /usr/share/migration-manager/ui/
	sudo cp -r ./ui/dist/* /usr/share/migration-manager/ui/

.PHONY: static-analysis
static-analysis: build-dependencies
ifeq ($(shell command -v go-licenses),)
	(cd / ; $(GO) install -v -x github.com/google/go-licenses@latest)
endif
ifeq ($(shell command -v golangci-lint),)
	curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $$($(GO) env GOPATH)/bin
endif
ifeq ($(shell command -v shellcheck),)
	echo "Please install shellcheck"
	exit 1
endif
	go-licenses check --disallowed_types=forbidden,unknown,restricted --ignore libguestfs.org/libnbd --ignore github.com/lxc/go-lxc --ignore github.com/rootless-containers/proto/go-proto ./...
	shellcheck --shell sh internal/worker/scripts/*.sh
	golangci-lint run ./...
	run-parts $(shell run-parts -V >/dev/null 2>&1 && echo -n "--verbose --exit-on-error --regex '\.sh$$' ") scripts/lint

.PHONY: vulncheck
vulncheck:
ifeq ($(shell command -v govulncheck),)
	go install golang.org/x/vuln/cmd/govulncheck@latest
endif
	govulncheck ./...

.PHONY: clean
clean:
	rm -rf dist/ bin/

.PHONY: release-snapshot
release-snapshot:
ifeq ($(shell command -v goreleaser),)
	echo "Please install goreleaser"
	exit 1
endif
	goreleaser release --snapshot --clean

.PHONY: build-dev-container
build-dev-container:
	docker build -t migration-manager-dev ./.devcontainer/

DOCKER_RUN := docker run -i -v .:/home/vscode/src --mount source=migration_manager_devcontainer_goroot,target=/go,type=volume --mount source=migration_manager_devcontainer_cache,target=/home/vscode/.cache,type=volume -w /home/vscode/src -u 1000:1000 migration-manager-dev

.PHONY: docker-build
docker-build: build-dev-container
	${DOCKER_RUN} make build

.PHONY: docker-build-ui
docker-build-ui: build-dev-container
	${DOCKER_RUN} make build-ui

.PHONY: docker-build-all-packages
docker-build-all-packages: build-dev-container
	${DOCKER_RUN} make build-all-packages

.PHONY: docker-test
docker-test: build-dev-container
	${DOCKER_RUN} make test

.PHONY: docker-static-analysis
docker-static-analysis: build-dev-container
	${DOCKER_RUN} make static-analysis

.PHONY: docker-release-snapshot
docker-release-snapshot: build-dev-container
	${DOCKER_RUN} make release-snapshot

.PHONY: enter-dev-container
enter-dev-container:
	@docker exec -it -w /workspaces/migration-manager ${USER}_migration_manager_devcontainer /bin/bash

# OpenFGA Syntax Transformer: https://github.com/openfga/syntax-transformer
.PHONY: update-openfga
update-openfga:
	@printf 'package auth\n\n// Code generated by Makefile; DO NOT EDIT.\n\nvar authModel = `%s`\n' '$(shell $(GO) run github.com/openfga/cli/cmd/fga model transform --file=./internal/server/auth/driver_openfga_model.openfga | jq -c)' > ./internal/server/auth/driver_openfga_model.go

.PHONY: update-gomod
update-gomod:
	$(GO) get -t -v -u ./...
	$(GO) get github.com/go-jose/go-jose/v4@v4.0.5
	$(GO) mod tidy --go=1.25.6
	$(GO) get toolchain@none

.PHONY: update-api
update-api:
	$(GO) install -v -x github.com/go-swagger/go-swagger/cmd/swagger@master
	swagger generate spec -o doc/rest-api.yaml -w ./cmd/migration-managerd/internal/api -m -x github.com/lxc/incus/v6/shared/api

.PHONY: doc-setup
doc-setup:
	@echo "Setting up documentation build environment"
	python3 -m venv doc/.sphinx/venv
	. $(SPHINXENV) ; pip install --require-virtualenv --upgrade -r doc/.sphinx/requirements.txt --log doc/.sphinx/venv/pip_install.log
	@test ! -f doc/.sphinx/venv/pip_list.txt || \
        mv doc/.sphinx/venv/pip_list.txt doc/.sphinx/venv/pip_list.txt.bak
	$(SPHINXPIPPATH) list --local --format=freeze > doc/.sphinx/venv/pip_list.txt
	rm -Rf doc/html
	rm -Rf doc/.sphinx/.doctrees

.PHONY: doc
doc: doc-setup doc-incremental

.PHONY: doc-incremental
doc-incremental:
	@echo "Build the documentation"
	. $(SPHINXENV) ; sphinx-build -c doc/ -b dirhtml doc/ doc/html/ -d doc/.sphinx/.doctrees -w doc/.sphinx/warnings.txt
	cp doc/rest-api.yaml doc/html/

.PHONY: doc-serve
doc-serve:
	cd doc/html; python3 -m http.server 8001

.PHONY: doc-spellcheck
doc-spellcheck: doc
	. $(SPHINXENV) ; python3 -m pyspelling -c doc/.sphinx/spellingcheck.yaml

.PHONY: doc-linkcheck
doc-linkcheck: doc-setup
	. $(SPHINXENV) ; LOCAL_SPHINX_BUILD=True sphinx-build -c doc/ -b linkcheck doc/ doc/html/ -d doc/.sphinx/.doctrees

.PHONY: doc-lint
doc-lint:
	doc/.sphinx/.markdownlint/doc-lint.sh
